#config_version=5

switches:
  s_left_flipper:
    number: 0-2
    tags: left_flipper
  s_right_flipper:
    number: 0-1
    tags: right_flipper
  s_3:
    number: 0-3
    tags: item_3
  s_8:
    number: 0-8
    tags: item_8
  s_9:
    number: 0-9
    tags: item_9
  s_10:
    number: 0-10
    tags: item_10
  s_11:
    number: 0-11
    tags: item_11
  s_16:
    number: 0-16
    tags: item_16
  s_17:
    number: 0-17
    tags: item_17
  s_18:
    number: 0-18
    tags: item_18
  s_19:
    number: 0-19
    tags: item_19
  s_24:
    number: 0-24
    tags: item_24
  s_25:
    number: 0-25
    tags: item_25
  s_26:
    number: 0-26
    tags: item_26
  s_27:
    number: 0-27
    tags: item_27

coils:
  c_flipper_left_main:
    number: 0-9  # again, these numbers will probably be different for you
    default_hold_power: 0.125
  c_flipper_right_main:
    number: 0-8
    default_hold_power: 0.125

playfields:
  playfield:
    tags: default
    default_source_device: None  # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

hardware:
  platform: opp

opp:
  ports: COM6
  debug: true
  poll_hz: 50